### ISSUE TITLE
new to python

### ISSUE THREAD

**Issue by btsimonh** [blassphemy/mqtt-ble-gateway#2]
hi, followed the instructions, but on running get

pi@raspberrypi:~/gateway/mqtt-ble-gateway $ python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import ble
  File "/home/pi/gateway/mqtt-ble-gateway/ble.py", line 9, in <module>
    from retrying import retry
ImportError: No module named retrying

tried sudo pip install ble, it installed something, but no different.
what am i missing?

OK; the names are confusing; it's obvious really - we need 
sudo pip install retrying

you could add it to the readme.

I also needed an MQTT user and password; e.g.
in start function:
    client.username_pw_set(username=MQTT_USER,password=MQTT_PWD)

**Comment by btsimonh** [comment]
but still not working correctly:
MQTT: connected
home/MQTTtoBLE/command/scan 1541593007272
starting full BLE scan!
found devices[{'name': None, 'address': u'00:1A:22:09:2F:AB'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2C:9A'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2F:06'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2F:B7'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2C:DB'}, {'name': None, 'address': u'00:1A:22:09:08:37'}, {'name': None, 'address': u'00:1A:22:09:2C:DF'}]
BLE scan: received not connected error!
reset connection to scan for new BLE devices!
found devices[{'name': None, 'address': u'00:1A:22:09:2F:AB'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2C:9A'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2F:06'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2F:B7'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2C:DB'}, {'name': None, 'address': u'00:1A:22:09:2C:DF'}]
BLE scan: received not connected error!
reset connection to scan for new BLE devices!
found devices[{'name': None, 'address': u'00:1A:22:09:2F:AB'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2C:9A'}, {'name': None, 'address': u'00:1A:22:09:2E:E0'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2F:06'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2F:B7'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2C:DB'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:08:37'}, {'name': u'CC-RT-M-BLE', 'address': u'00:1A:22:09:2C:DF'}]
BLE scan: received not connected error!
reset connection to scan for new BLE devices!
aborted BLE search because of multiple connection errors!

**Comment by btsimonh** [comment]
this is most likely an issues between pygatt and bluez 4.48?  in the reading of the connection text, maybe.
